bot:
  bot-name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  secure: false
  task-queue:
    default-bot-task-queue:
      task-execution-rate: 1000
      task-execution-time-unit: MILLISECONDS
  form-handler:
    enabled: true
logging:
  level:
    sun: info
    org:
      apache: info
    jdk: info
    javax: info
    root: debug